package com.GeekPaperAssistant.model.graph;

import org.springframework.data.neo4j.core.schema.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.UUID;

/**
 * 作者节点 - 知识图谱中的作者实体
 * 
 * @author 席崇援
 * @since 2025-10-16
 */
@Node("Author")
@Data
@EqualsAndHashCode(of = "id")
public class AuthorNode {
    
    @Id
    private String id;
    
    /**
     * 作者姓名
     */
    @Property("name")
    private String name;
    
    /**
     * 作者机构/单位
     */
    @Property("affiliation")
    private String affiliation;
    
    /**
     * 作者邮箱
     */
    @Property("email")
    private String email;
    
    /**
     * 研究领域
     */
    @Property("researchFields")
    private String researchFields;
    
    /**
     * H指数（学术影响力指标）
     */
    @Property("hIndex")
    private Integer hIndex;
    
    /**
     * 发表论文数量
     */
    @Property("publicationCount")
    private Integer publicationCount;
    
    
    public AuthorNode() {
        this.id = UUID.randomUUID().toString();
    }
    
    public AuthorNode(String name, String affiliation) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.affiliation = affiliation;
        this.publicationCount = 0;
        this.hIndex = 0;
    }
}

/**
 * 合作关系 - 作者间的合作关系属性
 */
@RelationshipProperties
@Data
class CollaborationRelation {
    
    @Id
    @GeneratedValue
    private Long id;
    
    /**
     * 合作次数
     */
    @Property("collaborationCount")
    private Integer collaborationCount;
    
    /**
     * 合作强度（0-1）
     */
    @Property("strength")
    private Double strength;
    
    /**
     * 首次合作时间
     */
    @Property("firstCollaboration")
    private String firstCollaboration;
    
    /**
     * 最近合作时间
     */
    @Property("lastCollaboration")
    private String lastCollaboration;
    
    public CollaborationRelation() {
        // id generated by Neo4j for relationship properties
    }
    
    /**
     * 合作伙伴
     */
    @TargetNode
    private AuthorNode collaborator;
}