package com.GeekPaperAssistant.model.graph;

import org.springframework.data.annotation.Version;
import org.springframework.data.neo4j.core.schema.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * 概念实体节点 - 知识图谱核心节点
 *
 * @author 席崇援
 * @since 2025-10-16
 */
@Node("Concept")
@Data
@EqualsAndHashCode(of = "id")
public class ConceptNode {

    @Id
    private String id;

    /**
     * 版本字段，用于乐观锁和判断实体是否为新实体
     * 第一次保存时为null，Spring Data Neo4j会将其视为新实体
     * 更新时会自动递增，用于检测并发修改
     */
    @Version
    private Long version;

    /**
     * 概念名称（唯一）
     */
    @Property("name")
    private String name;

    /**
     * 概念描述
     */
    @Property("description")
    private String description;

    /**
     * 概念类型：PERSON, ORGANIZATION, TECHNOLOGY, THEORY, METHOD, FIELD
     */
    @Property("type")
    private String type;

    /**
     * 所属学科领域
     */
    @Property("field")
    private String field;

    /**
     * 概念重要度评分（0-1）
     */
    @Property("importance")
    private Double importance;

    /**
     * 概念频次（在文档中出现的次数）
     */
    @Property("frequency")
    private Integer frequency;

    /**
     * 相关概念
     */
    @Relationship(type = "RELATED_TO")
    private Set<ConceptRelation> relatedConcepts = new HashSet<>();

    /**
     * 包含该概念的文档
     * 关系方向：Document-[:CONTAINS]->Concept
     */
    @Relationship(type = "CONTAINS", direction = Relationship.Direction.INCOMING)
    private Set<DocumentNode> documents = new HashSet<>();

    /**
     * 概念层次关系 - 父概念
     */
    @Relationship(type = "IS_A", direction = Relationship.Direction.OUTGOING)
    private Set<ConceptNode> parentConcepts = new HashSet<>();

    /**
     * 概念层次关系 - 子概念
     */
    @Relationship(type = "IS_A", direction = Relationship.Direction.INCOMING)
    private Set<ConceptNode> childConcepts = new HashSet<>();

    public ConceptNode() {
        this.id = UUID.randomUUID().toString();
    }

    public ConceptNode(String name, String type, String field) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.type = type;
        this.field = field;
        this.frequency = 1;
        this.importance = 0.5;
    }
}

/**
 * 概念关系 - 带权重的关系
 */
@RelationshipProperties
@Data
class ConceptRelation {

    @Id
    @GeneratedValue
    private Long id;

    /**
     * 关系类型：SIMILAR, OPPOSITE, PART_OF, USES, DEPENDS_ON
     */
    @Property("relationType")
    private String relationType;

    /**
     * 关系强度（0-1）
     */
    @Property("strength")
    private Double strength;

    /**
     * 关系置信度（0-1）
     */
    @Property("confidence")
    private Double confidence;

    public ConceptRelation() {
        // id will be generated by Neo4j (internal id for relationship properties)
    }

    /**
     * 目标概念
     */
    @TargetNode
    private ConceptNode targetConcept;
}
