package com.GeekPaperAssistant.model.graph;

import org.springframework.data.annotation.Version;
import org.springframework.data.neo4j.core.schema.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * 文档节点 - 知识图谱中的文档实体
 *
 * @author 席崇援
 * @since 2025-10-16
 */
@Node("Document")
@Data
@EqualsAndHashCode(of = "documentId")
public class DocumentNode {

    @Id
    private Long documentId; // 对应MySQL中的document.id

    /**
     * 版本字段，用于乐观锁和判断实体是否为新实体
     * 第一次保存时为null，Spring Data Neo4j会将其视为新实体
     * 更新时会自动递增，用于检测并发修改
     */
    @Version
    private Long version;

    /**
     * 文档标题
     */
    @Property("title")
    private String title;

    /**
     * 文档类型：research_paper, teaching_material, other
     */
    @Property("type")
    private String type;

    /**
     * 上传用户ID
     */
    @Property("userId")
    private Long userId;

    /**
     * 所属知识库ID
     */
    @Property("kbId")
    private Long kbId;

    /**
     * 创建时间
     */
    @Property("createTime")
    private LocalDateTime createTime;

    /**
     * 文档包含的概念
     */
    @Relationship(type = "CONTAINS")
    private Set<ConceptContainment> concepts = new HashSet<>();

    /**
     * 文档作者
     */
    @Relationship(type = "AUTHORED_BY", direction = Relationship.Direction.OUTGOING)
    private Set<AuthorNode> authors = new HashSet<>();

    public DocumentNode() {}

    public DocumentNode(Long documentId, String title, String type, Long userId) {
        this.documentId = documentId;
        this.title = title;
        this.type = type;
        this.userId = userId;
        this.createTime = LocalDateTime.now();
    }
}

/**
 * 概念包含关系 - 文档包含概念的关系属性
 */
@RelationshipProperties
@Data
class ConceptContainment {

    @Id
    @GeneratedValue
    private Long id;

    /**
     * 概念在文档中的重要性（0-1）
     */
    @Property("importance")
    private Double importance;

    /**
     * 概念在文档中出现的频次
     */
    @Property("frequency")
    private Integer frequency;

    /**
     * 概念提取的置信度（0-1）
     */
    @Property("confidence")
    private Double confidence;

    /**
     * 概念在文档中首次出现的位置
     */
    @Property("firstPosition")
    private Integer firstPosition;

    public ConceptContainment() {
        // id generated by Neo4j for relationship properties
    }

    /**
     * 目标概念
     */
    @TargetNode
    private ConceptNode concept;
}